language: python
os:
  - linux
before_install:
  - pip install --upgrade pip
install:
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r requirements-dev.txt
  - pip install --upgrade -r requirements-test.txt
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
branches:
  only:
    - master